from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from .models import Event
from .serializers import EventSerializer

class EventListCreateAPIView(generics.ListCreateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

class EventRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

class EventsAPIView(APIView):
    def get(self, request):
        events_data = [
            { 'key': 1, 'number': '1', 'name': 'Dan', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 16 },
            { 'key': 2, 'number': '2', 'name': 'Kaye', 'dog_name': 'Kibol', 'dog_breed': 'Brittany Spaniel', 'size': 16 },
            { 'key': 3, 'number': '3', 'name': 'Gonzales, Paul Rhayn', 'dog_name': 'Kibol', 'dog_breed': 'Brittany Spaniel', 'size': 6 },
            { 'key': 4, 'number': '4', 'name': 'Johnny', 'dog_name': 'Johnny', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 5, 'number': '5', 'name': 'Jim', 'dog_name': 'Medusa', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 6, 'number': '6', 'name': 'Hercules', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 7, 'number': '7', 'name': 'Medea', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 16 },
            { 'key': 8, 'number': '8', 'name': 'Medusa', 'dog_name': 'Kibol', 'dog_breed': 'Brittany Spaniel', 'size': 16 },
            { 'key': 9, 'number': '9', 'name': 'Kojirou', 'dog_name': 'Kibol', 'dog_breed': 'Brittany Spaniel', 'size': 6 },
            { 'key': 10, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 11, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 12, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 13, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 14, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 15, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 16, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 17, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 18, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 19, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 20, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 21, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 22, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 23, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 24, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 25, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 26, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 27, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 28, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 29, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 30, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 31, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 32, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 33, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 34, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 35, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 36, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 37, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 38, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 39, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 40, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 41, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 42, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 43, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 44, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 45, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 46, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 47, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 48, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 49, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 50, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 51, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 52, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 53, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 54, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 55, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 56, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 57, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 58, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 59, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 60, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 61, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 62, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 63, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 64, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 65, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 66, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 67, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 68, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 69, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 70, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 71, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 72, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 73, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 74, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 75, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 76, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 77, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 78, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 79, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 80, 'number': '10', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 81, 'number': '11', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 82, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 83, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 84, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 85, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 86, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 87, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 88, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 89, 'number': '12', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 90, 'number': '90', 'name': 'Scathach', 'dog_name': 'Hachi', 'dog_breed': 'Akita', 'size': 3.7 },
            { 'key': 91, 'number': '91', 'name': 'Emiya', 'dog_name': 'Hachi', 'dog_breed': 'Artoria Pendragon', 'size': 1.8 },
            { 'key': 92, 'number': '92', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 93, 'number': '93', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 94, 'number': '94', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 95, 'number': '95', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 96, 'number': '96', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 97, 'number': '97', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 98, 'number': '98', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 99, 'number': '99', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
            { 'key': 100, 'number': '100', 'name': 'Artoria', 'dog_name': 'Hachi', 'dog_breed': 'Emiya', 'size': 1.9 },
                # ... (your event data)
        ]

        serializer = EventSerializer(events_data, many=True)
        return Response({'events': serializer.data})
